services:

  my-sql:
    image: mysql
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - mysql_data:/var/lib/mysql 
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - my_network 
    
  my-node:
    build:
      context: node
    container_name: mynode  
    networks:
      - my_network 
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "8180:8180"
    depends_on:
      - my-sql
      

  my-nginx:
    build:
      context: nginx  
    container_name: meunginx
    ports:
      - "8080:80"
    networks:
      - my_network 
  
    depends_on:
      - my-node    

networks:
 my_network :
    driver: bridge  

volumes:
  mysql_data: 